apiVersion: apps/v1
kind: Deployment
metadata:
  name: washbin-site
  labels:
    app: washbinsite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: washbinsite
  template:
    metadata:
      labels:
        app: washbinsite
    spec:
      containers:
      - name: washbin
        imagePullPolicy: Always
        image: shettymanish01/testsite:latest
        ports:
        - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: washbin-service
spec:
  type: NodePort
  selector:
    app: washbinsite
  ports:
    - protocol: TCP
      port: 90
      targetPort: 5000
      nodePort: 31000
      
